version: "3.7"
services:
 api:
  build:
   context: .
   target: development
  volumes:
   - ./:/app
  depends_on:
      - db
  ports:
   - 3010:3010
  command: npm run dev
 app:
    build: .
    ports:
      - "3010:3010"
    environment:
      POSTGRES_URI: postgres://user:password@postgres:5432/postgres
      JWT_SECRET: abc
 postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" 
 db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
 adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080