name: Build and Push Docker Image
on:
push:
	branches:
		-main
jobs:	
	build:
		runs-on: ubuntu-lastest

		env:
			DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
			DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
		steps:
			- name: Checkout Repository
			  Uses: actions/checkou@v4
			- name: Build and Push Docker Image
			  Run: |
				docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
				docker build -t $DOCKER_USERNAME/techpost:lastest --build-arg MONGO_URI=${{ secrets.DATABASE_URL }} --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }}  .
				docker push $DOCKER_USERNAME/techpost:latest
